# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: acp-script
            asset_name: acp-script-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: acp-script
            asset_name: acp-script-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: acp-script
            asset_name: acp-script-macos-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create Universal Binary
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          # Wait for x86_64 build to complete
          while [ ! -f "target/x86_64-apple-darwin/release/${{ matrix.artifact_name }}" ]; do
            sleep 5
          done
          lipo -create \
            "target/x86_64-apple-darwin/release/${{ matrix.artifact_name }}" \
            "target/aarch64-apple-darwin/release/${{ matrix.artifact_name }}" \
            -output "universal-${{ matrix.artifact_name }}"
          tar -czf ${{ matrix.asset_name }}-universal.tar.gz "universal-${{ matrix.artifact_name }}"

      - name: Package Binary
        if: matrix.target != 'aarch64-apple-darwin'
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
          cd -

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.asset_name }}.tar.gz
            ${{ matrix.asset_name }}-universal.tar.gz
